/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatContent: typeof import('./src/components/ChatContent.vue')['default']
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElDrawer: (typeof import('element-plus/es'))['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: (typeof import('element-plus/es'))['ElTable']
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserList: typeof import('./src/components/UserList.vue')['default']
  }
}
